In [17]:
from word2number import w2n
import numpy as np
import pandas as pd
import math
from sklearn import linear_model

In [18]:
df = pd.read_csv("hiring_data.csv")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [19]:
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [20]:
df.median = math.floor(df.test_score.median())
df.median

8

In [21]:
df.test_score = df.test_score.fillna(df.median)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [22]:
df.experience = df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [23]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [24]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [25]:
reg.predict([[2,3,4]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([37721.25181951])

In [26]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [27]:
reg.intercept_

17737.263464337688

In [28]:
#y = m1*x1+m2*x2+m3*x3+c
2812.95487627*2+1845.70596798*3+2205.24017467*4+17737.263464337688

37721.25181949769

In [29]:
#All predicted values for dataset
input = [[0,8.0,9],[0,8.0,6],[5,6.0,7],[2,10.0,10],[7,9.0,6],[3,7.0,10],[10,8.0,7],[11,7.0,8]]
reg.predict(input)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52350.0727802 , 45734.35225619, 58312.95487627, 63872.63464338,
       67270.74235808, 61148.47161572, 76069.1411936 , 79241.63027656])